### ISSUE TITLE
docker 镜像的相关配置有吗

### ISSUE THREAD

**Issue by HeroBarry** [ThoreauZZ/spring-cloud-example#10]
Windows环境怎么干？在centos7中怎么搞？详细点就完美了

**Comment by ThoreauZZ** [comment]
@GeorgeMe 不需要了吧，
首先，不需要docker，都能在本地单独启动;
其次，如果安装了docker(不管在什么操作系统)，一条命令直接把所有镜像做好`mvn clean package`;
至于安装docker什么的就不用说了吧，欢迎参考我的博客[docker入门](http://thoreauz.com/2017/01/08/docker/Docker%E5%85%A5%E9%97%A8/)；

**Comment by HeroBarry** [comment]
我主要还是docker知识没有搞清楚  等搞清楚了来
