### ISSUE TITLE
comx.conf.json not existed

### ISSUE THREAD

**Issue by dream8062** [ThoreauZZ/spring-cloud-example#8]
When cloud-service-comx‘service  was  called ，the  error  appeared。

**Comment by ThoreauZZ** [comment]
fixed.
Please clone the latest version。
and 
curl -s 127.0.0.1:9006/ext/trade/order?id=1  or  curl -s 127.0.0.1:9019/ext/trade/order?id=1

**Comment by ThoreauZZ** [comment]
@dream8062 
fixed.
Please clone the latest version。

curl -s 127.0.0.1:9006/ext/trade/order?id=1 or curl -s 127.0.0.1:9019/ext/trade/order?id=1
